### ISSUE TITLE
ERR_OSSL_EVP_UNSUPPORTED when using Node 17

### ISSUE THREAD

**Issue by makkabi** [0phoff/MDXP#9]
´´´npm run start``` results in this error when using Node 17.9 (but also 17.0, so probably all Node 17 version), I had to switch to Node 16. Tested on an M1 Mac with macOS 12.3.1.

```
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/wwb/Projekte/my_presentation/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/wwb/Projekte/my_presentation/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/wwb/Projekte/my_presentation/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/wwb/Projekte/my_presentation/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/wwb/Projekte/my_presentation/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/wwb/Projekte/my_presentation/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/wwb/Projekte/my_presentation/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/wwb/Projekte/my_presentation/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by karlhorky** [comment]
I think this requires an update of webpack, is that accurate @0phoff ?
